# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
  end

  lane :update do
    update_fastlane
    clean_cocoapods_cache
    cocoapods
  end

  lane :test do
    run_tests(
            workspace: "Clexi.xcworkspace",
            scheme: "Clexi",
            clean: true)
  end

  desc "Build the project"
  lane :build do
    unlock_keychain(
	         path: "JenkinsCI.keychain-db",
	         password: "123456789")
    match
    gym(
        scheme: "Clexi",
        export_method: "development",
        export_xcargs: "-allowProvisioningUpdates")
  end

  lane :increase do
    increment_build_number
  end
end
